name: CrossWorkers Assessment

on:
  push:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add short sha env
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build final image
        run: |-
          docker build \
            --tag "docker.io/METoubar/assessment:$GITHUB_SHA" \
            --tag "docker.io/METoubar/assessment:latest" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "docker.io/METoubar/assessment:$GITHUB_SHA"
          docker push "docker.io/METoubar/assessment:latest"

      - name: Build & Deploy
        if: github.ref == 'refs/heads/master'
        working-directory: ./k8s
        run: |-
          kubectl apply -f .
